# -*- coding: utf-8 -*-
"""Copy of Gla_ML_Session1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13B1REh0NZC3gZwAodUvWwQhPZNtjALfV

Calculate the avg marks and prin t class fialed or passed is the avg is 50 or above
"""
import matplotlib.pyplot as plt
import pandas as pd

marks = [45, 60, 72, 38, 90]

total = 0

for i in range(len(marks) ):
    total += marks[i]

average = total / len(marks)

if average > 50:
    print("Class passed")
else:
    print("Class failed")

print("Average:", average)


data = {
    "student_id": [101, 102, 103, 104, 105, 106],
    "attendance_percent": [92, 67, 81, 45, 74, 88],
    "assignment_score": [18, 90, 15, 8, 14, 19],
    "quiz_score": [72, 87, 96, 30, 55, 80],
    "lab_completed": [True, False, True, False, True, True]
}

df = pd.DataFrame(data)

df

df.shape

df.head()

df.info()

df.describe()

df['total_score'] = df['assignment_score'] + df['quiz_score']
df

df['eligible'] = (
    (df['attendance_percent'] >= 75) &
    (df['total_score'] >= 70) &
    (df['lab_completed'])
)
df

eligible_students = df[df["eligible"] == True]
eligible_students

high_scorer=(df['assignment_score']>80) & (df['quiz_score']>80)
high_scorer

plt.plot(df["attendance_percent"],df["assignment_score"])
plt.xlabel("attendance_percent")
plt.ylabel("assignment_score")
plt.title("attendance_percent vs assignment_score")
plt.show()

plt.bar(df["attendance_percent"],df["quiz_score"])
plt.xlabel("attendance_percent")
plt.ylabel("quiz_score")
plt.title("attendance_percent vs quiz_score")
plt.show()

plt.plot(df["attendance_percent"],df["quiz_score"])
plt.xlabel("attendance_percent")
plt.ylabel("quiz_score")
plt.title("attendance_percent vs quiz_score")
plt.show()

plt.plot(df["attendance_percent"],df["total_score"])
plt.ylabel("attendance_percentt")
plt.xlabel("total_score")
plt.title("attendance_percent vs total_score")
plt.show()

plt.pie(df["attendance_percent"],labels=df["student_id"],autopct="%1.1f%%")
plt.title("attendance_percent pie_chart")
plt.show()

plt.pie(df["total_score"],labels=df["student_id"],autopct="%1.1f%%")
plt.title("total_score_percent pie_chart")
plt.show()